name: "Installs java, validates gradle wrapper, installs gradle dependencies with cache"
description: "Installs java, validates gradle wrapper, installs gradle dependencies with cache"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      id: setup-java
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: "gradle"
    - uses: gradle/wrapper-validation-action@v1.1.0
      id: gradle-wrapper-validation
    - uses: actions/cache@v3
      id: gradle-cache
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/.*gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
