name: "Installs node, installs yarn dependencies with chache"
description: "Builds a Next.JS App, creates a docker image and uploads it to GAR"

inputs:
  NPM_AUTH_TOKEN:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      id: setup-node
      with:
        node-version: 18.x
        cache: yarn
    - id: set-env
      shell: bash
      run: echo "NPM_AUTH_TOKEN=${{ inputs.NPM_AUTH_TOKEN }}" >> $GITHUB_ENV
    - uses: actions/cache@v3
      id: next-cache
      with:
        path: .next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-
    - id: yarn-install
      shell: bash
      run: yarn --immutable
