name: "Installs node, installs yarn dependencies with chache"
description: "Builds a Next.JS App, creates a docker image and uploads it to GAR"

inputs:
  NPM_AUTH_TOKEN:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - id: corepack
      shell: bash
      run: corepack enable
    - uses: actions/setup-node@v4
      id: setup-node
      with:
        node-version: 22.x
        cache: yarn
    - id: set-env
      shell: bash
      run: echo "NPM_AUTH_TOKEN=${{ inputs.NPM_AUTH_TOKEN }}" >> $GITHUB_ENV
    - id: yarn-install
      shell: bash
      run: yarn --immutable
