name: "Installs node, installs npm dependencies with cache"
description: "Builds a Next.JS App, creates a docker image and uploads it to GAR"

inputs:
  NPM_AUTH_TOKEN:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      id: setup-node
      with:
        node-version: 18.x
        cache: npm
    - id: set-env
      shell: bash
      run: echo "NPM_AUTH_TOKEN=${{ inputs.NPM_AUTH_TOKEN }}" >> $GITHUB_ENV
    - uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
    - id: npm-install
      shell: bash
      run: npm ci
