name: "Converts environment variables to a Kubernetes ConfigMap"
description: "Provide a .env.<env> file and this action will convert it to a Kubernetes ConfigMap"

inputs:
  app:
    required: true
    type: string
  env:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - id: verify-file-exists
      shell: bash
      run: |
        if [ ! -f "nais/envs/.env.${{ inputs.env }}" ]; then
          echo "File nais/envs/.env.${{ inputs.env }} does not exist"
          exit 1
        fi
    - id: convert-env-to-configmap
      shell: bash
      run: |
        echo "apiVersion: v1
        kind: ConfigMap
        metadata:
          labels:
            app: ${{ inputs.app }}
          name: ${{ inputs.app }}-config
          namespace: teamsykmelding
        data:
        $(cat nais/envs/.env.${{ inputs.env }} | sed 's/=/: /g' | sed 's/^/  /')" > nais/configmap.yaml
    - id: verify-configmap
      shell: bash
      run: |
        cat nais/configmap.yaml
