name: "Installs java, validates gradle wrapper, installs gradle dependencies with cache"
description: "Installs java, validates gradle wrapper, installs gradle dependencies with cache"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      id: setup-java
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: "gradle"
    - uses: actions/cache@v4
      id: gradle-cache
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/.*gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
