name: "Builds a jar, creates a docker image and uploads it to GAR"
description: "Builds a jar, creates a docker image and uploads it to GAR"

inputs:
  app:
    required: true
    type: string
  identity_provider:
    required: true
    type: string
  project_id:
    required: true
    type: string
outputs:
  image:
    description: "Docker image in GAR"
    value: ${{ steps.docker-build-push.outputs.image }}

runs:
  using: "composite"
  steps:
    - uses: navikt/teamsykmelding-github-actions-workflows/actions/gradle-typst-cached-21@main
    - name: Build jar
      env:
        COMMIT_SHA: ${{ github.sha }}
      shell: bash
      run: |
        ./gradlew installDist -x test
    - name: Setup Gradle to generate and submit dependency graphs
      uses: gradle/actions/setup-gradle@v4
      with:
        dependency-graph: generate-and-submit

    - name: Run a build, generating the dependency graph snapshot which will be submitted
      shell: bash
      run: ./gradlew build
    - name: Setup typst
      uses: typst-community/setup-typst@v5
      with:
          typst-version: 0.14.2
          
    - name: Copy typst binary
      shell: bash
      run: cp $(which typst) ./typst-pdf/typst
        
    - name: Push docker image to GAR
      uses: nais/docker-build-push@v0
      id: docker-build-push
      with:
        team: teamsykmelding
        salsa: true
        identity_provider: ${{ inputs.identity_provider }}
        project_id: ${{ inputs.project_id }}
