on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        language: ["kotlin"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'gradle'

      - name: Build
        run: |
          ./gradlew clean build --no-build-cache -x test

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{ matrix.language }}"

  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
    steps:
      - uses: navikt/teamsykmelding-github-actions-workflows/actions/gradle-cached-21@main
      - run: ./gradlew test
      - name: Summarize tests results
        uses: navikt/gradle-tests-summary@v1
        if: ${{ always() }}


  build-for-dependabot:
    if: github.actor == 'dependabot[bot]'
    name: Build for dependabot
    runs-on: ubuntu-latest
    steps:
      - uses: navikt/teamsykmelding-github-actions-workflows/actions/gradle-cached-21@main
      - name: Build jar
        shell: bash
        run: |
          ./gradlew installDist -x test

  build:
    if: github.actor != 'dependabot[bot]'
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: "write"
      contents: "write"
      id-token: "write"
    outputs:
      image: ${{ steps.build-and-publish.outputs.image }}
    steps:
      - uses: navikt/teamsykmelding-github-actions-workflows/actions/plain-jar-to-docker-21@main
        id: build-and-publish
        with:
          app: ${{ inputs.app }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  trivy-docker:
    name: Trivy
    permissions:
      id-token: 'write'
      security-events: 'write'
    needs: build
    uses: navikt/teamsykmelding-github-actions-workflows/.github/workflows/trivy-docker.yml@main
    with:
      image: ${{ needs.build.outputs.image }}
    secrets: inherit

  deploy-dev:
    name: Deploy to dev
    runs-on: ubuntu-latest
    needs: [ test, build ]
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: naiserator-dev.yaml
          VAR: image=${{ needs.build.outputs.image }},commit=${{ github.sha }},sourceVersionURL=https://github.com/${{ github.repository }}/tree/${{ github.sha }}

  deploy-prod:
    if: github.ref_name == 'main'
    name: Deploy to prod
    runs-on: ubuntu-latest
    needs: [ test, build ]
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: naiserator-prod.yaml
          VAR: image=${{ needs.build.outputs.image }},commit=${{ github.sha }},sourceVersionURL=https://github.com/${{ github.repository }}/tree/${{ github.sha }}
