name: "Installs node, installs yarn dependencies with chache"
description: "Builds a Next.JS App, creates a docker image and uploads it to GAR"

inputs:
  app:
    required: true
    type: string
  env:
    required: true
    type: string
  identity_provider:
    required: true
    type: string
  project_id:
    required: true
    type: string
  team:
    required: true
    default: "teamsykmelding"
  NPM_AUTH_TOKEN:
    required: true
    type: string
outputs:
  image:
    description: "Docker image in GAR"
    value: ${{ steps.docker-build-push.outputs.image }}

runs:
  using: "composite"
  steps:
    - uses: navikt/teamsykmelding-github-actions-workflows/actions/yarn-cached@main
      with:
        NPM_AUTH_TOKEN: ${{ inputs.NPM_AUTH_TOKEN }}
    - name: Copy appropriate env file to root
      shell: bash
      run: |
        echo "Copying .nais/envs/.env.${{ inputs.env }}..."
        cp .nais/envs/.env.${{ inputs.env }} .env.production
    - id: yarn-build
      shell: bash
      run: yarn build
      env:
        NEXT_PUBLIC_VERSION: ${{ github.sha }}
    - name: Upload static files to NAV CDN
      uses: nais/deploy/actions/cdn-upload/v2@master
      with:
        team: ${{ inputs.team }}
        source: ./.next/static
        destination: "/${{ inputs.app }}/_next"
        identity_provider: ${{ inputs.identity_provider }}
        project_id: ${{ inputs.project_id }}
    - name: Push docker image to GAR
      uses: nais/docker-build-push@v0
      env:
        ACTIONS_RUNTIME_TOKEN: ${{ inputs.NPM_AUTH_TOKEN  }}
        DOCKER_BUILD_SUMMARY: false
      id: docker-build-push
      with:
        team: ${{ inputs.team }}
        identity_provider: ${{ inputs.identity_provider }}
        project_id: ${{ inputs.project_id }}
        image_suffix: ${{ inputs.env }}
