name: "Installs node, installs npm dependencies with cache"
description: "Builds a Next.JS App, creates a docker image and uploads it to GAR"

inputs:
  app:
    required: true
    type: string
  env:
    required: true
    type: string
  identity_provider:
    required: true
    type: string
  project_id:
    required: true
    type: string
  NPM_AUTH_TOKEN:
    required: true
    type: string
outputs:
  image:
    description: "Docker image in GAR"
    value: ${{ steps.docker-build-push.outputs.image }}

runs:
  using: "composite"
  steps:
    - uses: navikt/teamesyfo-github-actions-workflows/actions/npm-cached@main
      with:
        NPM_AUTH_TOKEN: ${{ inputs.NPM_AUTH_TOKEN }}
    - name: Copy appropriate env file to root
      shell: bash
      run: |
        echo "Copying nais/envs/.env.${{ inputs.env }}..."
        cp nais/envs/.env.${{ inputs.env }} .env.production
    - id: npm-build
      shell: bash
      run: npm run build
      env:
        NEXT_PUBLIC_VERSION: ${{ github.sha }}
    - name: Upload static files to NAV CDN
      uses: navikt/frontend/actions/cdn-upload/v1@main
      with:
        cdn-team-name: team-esyfo
        source: ./.next/static
        destination: "/${{ inputs.app }}/_next"
    - name: Push docker image to GAR
      uses: nais/docker-build-push@v0
      id: docker-build-push
      with:
        team: team-esyfo
        identity_provider: ${{ inputs.identity_provider }}
        project_id: ${{ inputs.project_id }}
        image_suffix: ${{ inputs.env }}
